#!/bin/bash
youtube-dl -f 'best[height<=720]' --youtube-skip-dash-manifest --no-check-certificate --playlist-end $1 --playlist-reverse --no-playlist -cio '%(upload_date)s-%(uploader)s-%(title)s.%(ext)s' --batch-file subs.txt --download-archive archive.txt
youtube-dl -f 'best[height<=720]' --youtube-skip-dash-manifest --no-check-certificate --playlist-start $1 --playlist-reverse --no-playlist -cio '%(upload_date)s-%(uploader)s-%(title)s.%(ext)s' --batch-file subs-pr.txt --download-archive archive.txt
#youtube-dl -f 'best[height<=720]' --youtube-skip-dash-manifest --no-check-certificate --playlist-end $1 --no-playlist -cio '%(upload_date)s-%(uploader)s-%(title)s.%(ext)s'

