#
# Tmux Configuration
#

##--------------##
#    KEYBINDS    #
##--------------##

# ** Note: do not use Alt-bindings b, f, d, y, ".", r, *, or ?
# **  These are used already by the OS

# bind vi-like pane movement
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# resize binds
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5

# split windows
bind | split-window -h
bind - split-window -v


##---------------##
#    AESTHETIC    #
##---------------##

# Inactive Border Colour
set-option -g pane-border-fg colour4
# Active Border Colour
set-option -g pane-active-border-fg colour1

##############
# Status Bar #
##############

# Interval
set-option -g status-interval 10

# Activity Notifications
setw -g monitor-activity on
set -g visual-activity on

# Colours
set-option -g status-fg colour1
set-option -g status-bg colour0

set-window-option -g window-status-fg colour8
set-window-option -g window-status-bg colour0

set-window-option -g window-status-current-fg colour0
set-window-option -g window-status-current-bg colour1

# Move bar to the top
set-option -g status-position top

# Statusline
set -g status-right-length 130
set -g status-right "#(curl checkip.amazonaws.com) #[fg=colour8]|#[fg=colour1] #(curl icanhazip.com) #[fg=colour8]|#[fg=colour1] mem #(free -h | grep Mem | awk '{print $3}') #[fg=colour8]|#[fg=colour1] swap #(free -h | grep Swap | awk '{print $3}') #[fg=colour8]|#[fg=colour1] home #(du -sh /home/cooro | awk '{print $1;}') #[fg=colour8]|#[fg=colour1] %Y.%m.%d %H:%M:%S"

